export interface ComponentMeta {
  slug: string;
  name: string;
  description: string;
  docsUrl: string;
  installed: boolean;
}

export const componentsRegistry: ComponentMeta[] = [
  {
    slug: "accordion",
    name: "Accordion",
    description: "A vertically stacked set of interactive headings that each reveal a section of content.",
    docsUrl: "https://ui.shadcn.com/docs/components/accordion",
    installed: true,
  },
  {
    slug: "alert",
    name: "Alert",
    description: "Displays a callout for user attention.",
    docsUrl: "https://ui.shadcn.com/docs/components/alert",
    installed: true,
  },
  {
    slug: "alert-dialog",
    name: "Alert Dialog",
    description: "A modal dialog that interrupts the user with important content and expects a response.",
    docsUrl: "https://ui.shadcn.com/docs/components/alert-dialog",
    installed: true,
  },
  {
    slug: "aspect-ratio",
    name: "Aspect Ratio",
    description: "Displays content within a desired ratio.",
    docsUrl: "https://ui.shadcn.com/docs/components/aspect-ratio",
    installed: true,
  },
  {
    slug: "avatar",
    name: "Avatar",
    description: "An image element with a fallback for representing the user.",
    docsUrl: "https://ui.shadcn.com/docs/components/avatar",
    installed: true,
  },
  {
    slug: "badge",
    name: "Badge",
    description: "Displays a badge or a component that looks like a badge.",
    docsUrl: "https://ui.shadcn.com/docs/components/badge",
    installed: true,
  },
  {
    slug: "breadcrumb",
    name: "Breadcrumb",
    description: "Displays the path to the current resource using a hierarchy of links.",
    docsUrl: "https://ui.shadcn.com/docs/components/breadcrumb",
    installed: true,
  },
  {
    slug: "button",
    name: "Button",
    description: "Displays a button or a component that looks like a button.",
    docsUrl: "https://ui.shadcn.com/docs/components/button",
    installed: true,
  },
  {
    slug: "button-group",
    name: "Button Group",
    description: "A container that groups related buttons together with consistent styling.",
    docsUrl: "https://ui.shadcn.com/docs/components/button-group",
    installed: true,
  },
  {
    slug: "calendar",
    name: "Calendar",
    description: "A calendar component that allows users to select a date or a range of dates.",
    docsUrl: "https://ui.shadcn.com/docs/components/calendar",
    installed: true,
  },
  {
    slug: "card",
    name: "Card",
    description: "Displays a card with header, content, and footer.",
    docsUrl: "https://ui.shadcn.com/docs/components/card",
    installed: true,
  },
  {
    slug: "carousel",
    name: "Carousel",
    description: "A carousel with motion and swipe built using Embla.",
    docsUrl: "https://ui.shadcn.com/docs/components/carousel",
    installed: true,
  },
  {
    slug: "chart",
    name: "Chart",
    description: "Beautiful charts. Built using Recharts. Copy and paste into your apps.",
    docsUrl: "https://ui.shadcn.com/docs/components/chart",
    installed: true,
  },
  {
    slug: "checkbox",
    name: "Checkbox",
    description: "A control that allows the user to toggle between checked and not checked.",
    docsUrl: "https://ui.shadcn.com/docs/components/checkbox",
    installed: true,
  },
  {
    slug: "collapsible",
    name: "Collapsible",
    description: "An interactive component which expands/collapses a panel.",
    docsUrl: "https://ui.shadcn.com/docs/components/collapsible",
    installed: true,
  },
  {
    slug: "combobox",
    name: "Combobox",
    description: "Autocomplete input with a list of suggestions.",
    docsUrl: "https://ui.shadcn.com/docs/components/combobox",
    installed: false,
  },
  {
    slug: "command",
    name: "Command",
    description: "Command menu for search and quick actions.",
    docsUrl: "https://ui.shadcn.com/docs/components/command",
    installed: true,
  },
  {
    slug: "context-menu",
    name: "Context Menu",
    description: "Displays a menu of actions triggered by a right click.",
    docsUrl: "https://ui.shadcn.com/docs/components/context-menu",
    installed: true,
  },
  {
    slug: "data-table",
    name: "Data Table",
    description: "Powerful table and datagrids built using TanStack Table.",
    docsUrl: "https://ui.shadcn.com/docs/components/data-table",
    installed: false,
  },
  {
    slug: "date-picker",
    name: "Date Picker",
    description: "A date picker component with range and presets.",
    docsUrl: "https://ui.shadcn.com/docs/components/date-picker",
    installed: false,
  },
  {
    slug: "dialog",
    name: "Dialog",
    description: "A window overlaid on either the primary window or another dialog window.",
    docsUrl: "https://ui.shadcn.com/docs/components/dialog",
    installed: true,
  },
  {
    slug: "direction",
    name: "Direction",
    description: "A provider component that sets the text direction for your application.",
    docsUrl: "https://ui.shadcn.com/docs/components/direction",
    installed: false,
  },
  {
    slug: "drawer",
    name: "Drawer",
    description: "A drawer component for React.",
    docsUrl: "https://ui.shadcn.com/docs/components/drawer",
    installed: true,
  },
  {
    slug: "dropdown-menu",
    name: "Dropdown Menu",
    description: "Displays a menu to the user triggered by a button.",
    docsUrl: "https://ui.shadcn.com/docs/components/dropdown-menu",
    installed: true,
  },
  {
    slug: "empty",
    name: "Empty",
    description: "Use the Empty component to display an empty state.",
    docsUrl: "https://ui.shadcn.com/docs/components/empty",
    installed: true,
  },
  {
    slug: "field",
    name: "Field",
    description: "Combine labels, controls, and help text to compose accessible form fields.",
    docsUrl: "https://ui.shadcn.com/docs/components/field",
    installed: true,
  },
  {
    slug: "hover-card",
    name: "Hover Card",
    description: "For sighted users to preview content available behind a link.",
    docsUrl: "https://ui.shadcn.com/docs/components/hover-card",
    installed: true,
  },
  {
    slug: "input",
    name: "Input",
    description: "A text input component for forms and user data entry.",
    docsUrl: "https://ui.shadcn.com/docs/components/input",
    installed: true,
  },
  {
    slug: "input-group",
    name: "Input Group",
    description: "Add addons, buttons, and helper content to inputs.",
    docsUrl: "https://ui.shadcn.com/docs/components/input-group",
    installed: true,
  },
  {
    slug: "input-otp",
    name: "Input OTP",
    description: "Accessible one-time password component with copy-paste functionality.",
    docsUrl: "https://ui.shadcn.com/docs/components/input-otp",
    installed: true,
  },
  {
    slug: "item",
    name: "Item",
    description: "A versatile component for displaying content with media, title, description, and actions.",
    docsUrl: "https://ui.shadcn.com/docs/components/item",
    installed: true,
  },
  {
    slug: "kbd",
    name: "Kbd",
    description: "Used to display textual user input from keyboard.",
    docsUrl: "https://ui.shadcn.com/docs/components/kbd",
    installed: true,
  },
  {
    slug: "label",
    name: "Label",
    description: "Renders an accessible label associated with controls.",
    docsUrl: "https://ui.shadcn.com/docs/components/label",
    installed: true,
  },
  {
    slug: "menubar",
    name: "Menubar",
    description: "A visually persistent menu common in desktop applications.",
    docsUrl: "https://ui.shadcn.com/docs/components/menubar",
    installed: true,
  },
  {
    slug: "native-select",
    name: "Native Select",
    description: "A styled native HTML select element.",
    docsUrl: "https://ui.shadcn.com/docs/components/native-select",
    installed: false,
  },
  {
    slug: "navigation-menu",
    name: "Navigation Menu",
    description: "A collection of links for navigating websites.",
    docsUrl: "https://ui.shadcn.com/docs/components/navigation-menu",
    installed: true,
  },
  {
    slug: "pagination",
    name: "Pagination",
    description: "Pagination with page navigation, next and previous links.",
    docsUrl: "https://ui.shadcn.com/docs/components/pagination",
    installed: true,
  },
  {
    slug: "popover",
    name: "Popover",
    description: "Displays rich content in a portal, triggered by a button.",
    docsUrl: "https://ui.shadcn.com/docs/components/popover",
    installed: true,
  },
  {
    slug: "progress",
    name: "Progress",
    description: "Displays an indicator showing the completion progress of a task.",
    docsUrl: "https://ui.shadcn.com/docs/components/progress",
    installed: true,
  },
  {
    slug: "radio-group",
    name: "Radio Group",
    description: "A set of checkable buttons where no more than one can be checked at a time.",
    docsUrl: "https://ui.shadcn.com/docs/components/radio-group",
    installed: true,
  },
  {
    slug: "resizable",
    name: "Resizable",
    description: "Accessible resizable panel groups and layouts with keyboard support.",
    docsUrl: "https://ui.shadcn.com/docs/components/resizable",
    installed: true,
  },
  {
    slug: "scroll-area",
    name: "Scroll Area",
    description: "Augments native scroll functionality for custom, cross-browser styling.",
    docsUrl: "https://ui.shadcn.com/docs/components/scroll-area",
    installed: true,
  },
  {
    slug: "select",
    name: "Select",
    description: "Displays a list of options for the user to pick from.",
    docsUrl: "https://ui.shadcn.com/docs/components/select",
    installed: true,
  },
  {
    slug: "separator",
    name: "Separator",
    description: "Visually or semantically separates content.",
    docsUrl: "https://ui.shadcn.com/docs/components/separator",
    installed: true,
  },
  {
    slug: "sheet",
    name: "Sheet",
    description: "Extends the Dialog component to display content that complements the main content.",
    docsUrl: "https://ui.shadcn.com/docs/components/sheet",
    installed: true,
  },
  {
    slug: "sidebar",
    name: "Sidebar",
    description: "A composable, themeable and customizable sidebar component.",
    docsUrl: "https://ui.shadcn.com/docs/components/sidebar",
    installed: true,
  },
  {
    slug: "skeleton",
    name: "Skeleton",
    description: "Use to show a placeholder while content is loading.",
    docsUrl: "https://ui.shadcn.com/docs/components/skeleton",
    installed: true,
  },
  {
    slug: "slider",
    name: "Slider",
    description: "An input where the user selects a value from within a given range.",
    docsUrl: "https://ui.shadcn.com/docs/components/slider",
    installed: true,
  },
  {
    slug: "sonner",
    name: "Sonner",
    description: "An opinionated toast component for React.",
    docsUrl: "https://ui.shadcn.com/docs/components/sonner",
    installed: true,
  },
  {
    slug: "spinner",
    name: "Spinner",
    description: "An indicator that can be used to show a loading state.",
    docsUrl: "https://ui.shadcn.com/docs/components/spinner",
    installed: true,
  },
  {
    slug: "switch",
    name: "Switch",
    description: "A control that allows the user to toggle between checked and not checked.",
    docsUrl: "https://ui.shadcn.com/docs/components/switch",
    installed: true,
  },
  {
    slug: "table",
    name: "Table",
    description: "A responsive table component.",
    docsUrl: "https://ui.shadcn.com/docs/components/table",
    installed: true,
  },
  {
    slug: "tabs",
    name: "Tabs",
    description: "A set of layered sections of content displayed one at a time.",
    docsUrl: "https://ui.shadcn.com/docs/components/tabs",
    installed: true,
  },
  {
    slug: "textarea",
    name: "Textarea",
    description: "Displays a form textarea or a component that looks like a textarea.",
    docsUrl: "https://ui.shadcn.com/docs/components/textarea",
    installed: true,
  },
  {
    slug: "toast",
    name: "Toast",
    description: "A succinct message that is displayed temporarily.",
    docsUrl: "https://ui.shadcn.com/docs/components/toast",
    installed: false,
  },
  {
    slug: "toggle",
    name: "Toggle",
    description: "A two-state button that can be either on or off.",
    docsUrl: "https://ui.shadcn.com/docs/components/toggle",
    installed: true,
  },
  {
    slug: "toggle-group",
    name: "Toggle Group",
    description: "A set of two-state buttons that can be toggled on or off.",
    docsUrl: "https://ui.shadcn.com/docs/components/toggle-group",
    installed: true,
  },
  {
    slug: "tooltip",
    name: "Tooltip",
    description: "A popup that displays information related to an element when the element receives keyboard focus or the mouse hovers over it.",
    docsUrl: "https://ui.shadcn.com/docs/components/tooltip",
    installed: true,
  },
  {
    slug: "typography",
    name: "Typography",
    description: "Styles for headings, paragraphs, lists, etc.",
    docsUrl: "https://ui.shadcn.com/docs/components/typography",
    installed: false,
  },
];
